/**
 * @hadk/agent-adapters — generates coding-agent instruction files.
 *
 * One canonical protocol source (HACKATHON.md) is the single source of
 * truth; adapter-specific wrappers (.claude/, .codex/, .agents/,
 * AGENTS.md) reference it rather than duplicating instructions.
 */

import { type Result, ok, nowIso, SUPPORTED_AGENTS } from '@hadk/core';
import { StateStore } from '@hadk/state-store';
import { mkdirSync, writeFileSync, existsSync, readFileSync, statSync, accessSync, constants } from 'node:fs';
import { join, delimiter } from 'node:path';

export interface AdapterResult {
  files_written: string[];
  detected_agents: string[];
}

export class AgentAdapters {
  constructor(private store: StateStore) {}

  /**
   * Generate AGENTS.md, HACKATHON.md, and per-agent wrapper files.
   * Non-destructive: existing files are preserved unless they are
   * HADK-generated (marked with a generator header).
   */
  install(): Result<AdapterResult> {
    const root = this.store.projectRoot;
    const filesWritten: string[] = [];
    const detected = this.detectAgents(root);

    if (detected.length === 0) {
      this.store.log('adapters', 'No supported coding agents detected; no instruction files created.');
      return ok({ files_written: filesWritten, detected_agents: detected });
    }

    // Canonical protocol source
    const hackathonMd = join(root, 'HACKATHON.md');
    if (this.writeIfManaged(hackathonMd, this.canonicalProtocol())) filesWritten.push('HACKATHON.md');

    // AGENTS.md — generic entry point referencing the canonical protocol
    const agentsMd = join(root, 'AGENTS.md');
    if (this.writeIfManaged(agentsMd, this.agentsMd())) filesWritten.push('AGENTS.md');

    // Claude Code adapter
    if (detected.includes('claude-code')) {
      const claudeDir = join(root, '.claude');
      mkdirSync(claudeDir, { recursive: true });
      const claudeInstructions = join(claudeDir, 'HACKATHON.md');
      if (this.writeIfManaged(claudeInstructions, this.claudeWrapper())) filesWritten.push('.claude/HACKATHON.md');
    }

    // Codex adapter
    if (detected.includes('codex')) {
      const codexDir = join(root, '.codex');
      mkdirSync(codexDir, { recursive: true });
      const codexInstructions = join(codexDir, 'HACKATHON.md');
      if (this.writeIfManaged(codexInstructions, this.codexWrapper())) filesWritten.push('.codex/HACKATHON.md');
    }

    // OpenCode / generic .agents adapter
    if (detected.includes('opencode')) {
      const agentsDir = join(root, '.agents');
      mkdirSync(agentsDir, { recursive: true });
      const openCodeInstructions = join(agentsDir, 'HACKATHON.md');
      if (this.writeIfManaged(openCodeInstructions, this.openCodeWrapper())) filesWritten.push('.agents/HACKATHON.md');
    }

    this.store.log('adapters', `Installed agent adapters for: ${detected.join(', ') || 'generic'}.`);
    return ok({ files_written: filesWritten, detected_agents: detected });
  }

  detectAgents(root: string): string[] {
    const found: string[] = [];
    if (existsSync(join(root, '.claude')) || commandExists('claude')) found.push('claude-code');
    if (existsSync(join(root, '.codex')) || commandExists('codex')) found.push('codex');
    if (existsSync(join(root, '.agents')) || commandExists('opencode')) found.push('opencode');
    return [...new Set(found)];
  }

  // ─── Content Generators ────────────────────────────────────────────────

  private header(): string {
    return `<!-- GENERATED BY HADK (hadk setup) — ${nowIso()} -->
<!-- Do not edit manually; re-run \`hadk setup\` to regenerate. -->
`;
  }

  private canonicalProtocol(): string {
    return `${this.header()}# HADK Competition Protocol

This project is managed by the **HADK Competition Engineering Harness**.

## Canonical State

The single source of truth is \`.hackathon/state.yaml\`. Never rely on chat
history for project state — always read the state file first.

## Discover Current Context

1. Read \`.hackathon/state.yaml\` — competition, strategy, scope, phase, gates.
2. Read \`.hackathon/artifacts/\` — persisted outputs per phase.
3. Run \`hadk status\` — human-readable summary.
4. Run \`hadk next\` — the correct next action given actual state.

## Phase Model

\`\`\`
setup → competition-intelligence → strategy → idea → scope →
architecture → scaffold → build → demo → video → judge → submission → complete
\`\`\`

## Rules

- Do not advance a phase until its gate passes (\`hadk validate <gate>\`).
- Do not modify locked scope without an explicit \`hadk replan\`.
- Do not overwrite user code — the scaffold is non-destructive.
- Respect the deadline policy reported by \`hadk status\`.
- Persist every important artifact under \`.hackathon/artifacts/\`.
- Create a checkpoint before risky operations: \`hadk checkpoint\`.

## Allowed Operations by Deadline

\`hadk status\` reports the current deadline mode. When time is short the
harness restricts operations (e.g. submission-only under 1 hour). Follow it.

## Artifact Locations

| Artifact | Path |
|---|---|
| State | \`.hackathon/state.yaml\` |
| Competition intel | \`.hackathon/artifacts/competition/\` |
| Strategy | \`.hackathon/artifacts/strategy/\` |
| Ideas | \`.hackathon/artifacts/ideas/\` |
| Scope | \`.hackathon/artifacts/scope/\` |
| Architecture | \`.hackathon/artifacts/architecture/\` |
| Demo | \`.hackathon/artifacts/demo/\` |
| Submission | \`.hackathon/artifacts/submission/\` |
| Generated prototype | \`prototype/\` |
| Demo video | \`demo-video/\` |
`;
  }

  private agentsMd(): string {
    return `${this.header()}# Agent Instructions

This repository uses the HADK harness. The canonical protocol lives in
[HACKATHON.md](./HACKATHON.md) — read it before making changes.

Quick orientation:

\`\`\`bash
hadk status   # current phase, gate, deadline mode, next action
hadk next     # the single correct next step
\`\`\`

Supported agents: ${SUPPORTED_AGENTS.join(', ')}. Each has a thin wrapper
under its config directory that points back to HACKATHON.md (no duplication).
`;
  }

  private claudeWrapper(): string {
    return `${this.header()}# Claude Code — HADK Wrapper

Read the canonical protocol at the repository root: [HACKATHON.md](../HACKATHON.md).

Before any task:
1. \`cat .hackathon/state.yaml\` (or read it) to load current state.
2. Run \`hadk next\` to confirm the correct action.
3. Follow gate and deadline rules from the protocol.
`;
  }

  private codexWrapper(): string {
    return `${this.header()}# Codex — HADK Wrapper

Read the canonical protocol at the repository root: [HACKATHON.md](../HACKATHON.md).

Before any task:
1. Read \`.hackathon/state.yaml\` for current state.
2. Run \`hadk next\` for the correct action.
3. Follow gate and deadline rules from the protocol.
`;
  }

  private openCodeWrapper(): string {
    return `${this.header()}# OpenCode — HADK Wrapper

Read the canonical protocol at the repository root: [HACKATHON.md](../HACKATHON.md).

Before any task:
1. Read \`.hackathon/state.yaml\` for current state.
2. Run \`hadk next\` for the correct action.
3. Follow gate and deadline rules from the protocol.
`;
  }

  // ─── Safe Write ────────────────────────────────────────────────────────

  private writeIfManaged(path: string, content: string): boolean {
    if (existsSync(path)) {
      const existing = readSafe(path);
      // Only overwrite files we generated (marked with the header)
      if (!existing.includes('GENERATED BY HADK')) {
        return false; // preserve user file
      }
    }
    writeFileSync(path, content, 'utf-8');
    return true;
  }
}

function readSafe(path: string): string {
  try {
    return readFileSync(path, 'utf-8');
  } catch {
    return '';
  }
}

/**
 * Check whether a command exists on PATH without invoking a shell.
 */
function commandExists(cmd: string): boolean {
  const pathDirs = (process.env.PATH ?? '').split(delimiter);
  for (const dir of pathDirs) {
    if (!dir) continue;
    const candidate = join(dir, cmd);
    try {
      accessSync(candidate, constants.X_OK);
      if (statSync(candidate).isFile()) return true;
    } catch {
      // not found in this dir
    }
  }
  return false;
}
