/**
 * Profile: web-ai-fullstack — Next.js full-stack with AI integration.
 */

import type { FeatureMapping, ScaffoldFile } from '@hadk/core';
import { type ProfileContext, type ProfileDefinition, mkFile, featureComponentName } from './profiles.js';

function generateFiles(ctx: ProfileContext): ScaffoldFile[] {
  const { projectName, features, featureMapping, demoFlow, wowMoment } = ctx;
  const files: ScaffoldFile[] = [];

  // ─── package.json ──────────────────────────────────────────────────────
  files.push(mkFile('package.json', JSON.stringify({
    name: projectName,
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      lint: 'next lint',
      typecheck: 'tsc --noEmit',
      test: 'vitest run',
      'demo:reset': 'tsx scripts/reset-demo-data.ts',
      'demo:seed': 'tsx scripts/seed-demo-data.ts',
    },
    dependencies: {
      next: '^15.1.0',
      react: '^19.0.0',
      'react-dom': '^19.0.0',
      zod: '^3.24.0',
    },
    devDependencies: {
      '@types/node': '^22.10.0',
      '@types/react': '^19.0.0',
      '@types/react-dom': '^19.0.0',
      typescript: '^5.7.0',
      vitest: '^3.0.0',
      tsx: '^4.19.0',
      tailwindcss: '^4.0.0',
      '@tailwindcss/postcss': '^4.0.0',
    },
  }, null, 2) + '\n'));

  // ─── tsconfig.json ─────────────────────────────────────────────────────
  files.push(mkFile('tsconfig.json', JSON.stringify({
    compilerOptions: {
      target: 'ES2022',
      lib: ['dom', 'dom.iterable', 'esnext'],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'preserve',
      incremental: true,
      plugins: [{ name: 'next' }],
      paths: { '@/*': ['./src/*'] },
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
    exclude: ['node_modules'],
  }, null, 2) + '\n'));

  // ─── next.config.ts ────────────────────────────────────────────────────
  files.push(mkFile('next.config.ts', `import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  reactStrictMode: true,
};

export default nextConfig;
`));

  // ─── Environment template ──────────────────────────────────────────────
  files.push(mkFile('.env.example', `# ${projectName} — environment configuration
# Copy to .env.local and fill in values.

# AI provider — set any ONE key. Auto-detected in this order:
# Anthropic (Claude) → Mistral → OpenAI-compatible.
# Force a specific provider with AI_PROVIDER=anthropic|mistral|openai
ANTHROPIC_API_KEY=
ANTHROPIC_MODEL=claude-sonnet-5
MISTRAL_API_KEY=
MISTRAL_MODEL=mistral-large-latest
OPENAI_API_KEY=
OPENAI_BASE_URL=https://api.openai.com/v1
OPENAI_MODEL=gpt-4o-mini

# Fallback mode: set to "true" for deterministic offline responses (no key, no network)
DEMO_FALLBACK_MODE=false

# App
NEXT_PUBLIC_APP_NAME=${projectName}
`));

  files.push(mkFile('.env.local', `# Local development defaults (fallback mode — works without API keys)
ANTHROPIC_API_KEY=
MISTRAL_API_KEY=
OPENAI_API_KEY=
DEMO_FALLBACK_MODE=true
NEXT_PUBLIC_APP_NAME=${projectName}
`));

  // ─── App shell ─────────────────────────────────────────────────────────
  files.push(mkFile('src/app/layout.tsx', `import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: '${projectName}',
  description: 'Generated by HADK scaffold engine',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`));

  files.push(mkFile('src/app/globals.css', `@import 'tailwindcss';

:root {
  --background: #0a0a0f;
  --foreground: #ededed;
  --accent: #6366f1;
}

body {
  background: var(--background);
  color: var(--foreground);
  font-family: 'Inter', system-ui, sans-serif;
}
`));

  files.push(mkFile('src/app/page.tsx', `import { DemoPanel } from '@/components/demo-panel';

export default function Home() {
  return (
    <main className="min-h-screen flex flex-col items-center justify-center p-8">
      <h1 className="text-4xl font-bold mb-2">${projectName}</h1>
      <p className="text-neutral-400 mb-8">Hackathon prototype — demo path below</p>
      <DemoPanel />
    </main>
  );
}
`));

  // ─── Health endpoint ───────────────────────────────────────────────────
  files.push(mkFile('src/app/api/health/route.ts', `import { NextResponse } from 'next/server';

export async function GET() {
  return NextResponse.json({
    status: 'ok',
    service: '${projectName}',
    timestamp: new Date().toISOString(),
    fallback_mode: process.env.DEMO_FALLBACK_MODE === 'true',
  });
}
`));

  // ─── Core AI service with fallback ─────────────────────────────────────
  files.push(mkFile('src/core/ai/client.ts', `/**
 * Multi-provider AI client with a deterministic offline fallback.
 *
 * Provider auto-detection order: Anthropic (Claude) → Mistral → OpenAI-compatible.
 * Force one with AI_PROVIDER=anthropic|mistral|openai. Uses plain fetch — no SDK
 * dependency. When DEMO_FALLBACK_MODE=true or no key is set, responses are
 * deterministic and derived from the input, so the demo works with the wifi down.
 */

export interface AiRequest {
  prompt: string;
  context?: string;
}

export interface AiResponse {
  text: string;
  model: string;
  provider: string;
  fallback: boolean;
  latency_ms: number;
}

type Provider = 'anthropic' | 'mistral' | 'openai';

const PROVIDER_KEYS: Record<Provider, string> = {
  anthropic: 'ANTHROPIC_API_KEY',
  mistral: 'MISTRAL_API_KEY',
  openai: 'OPENAI_API_KEY',
};

function detectProvider(): Provider | null {
  const forced = process.env.AI_PROVIDER as Provider | undefined;
  if (forced && PROVIDER_KEYS[forced] && process.env[PROVIDER_KEYS[forced]]) return forced;
  if (process.env.ANTHROPIC_API_KEY) return 'anthropic';
  if (process.env.MISTRAL_API_KEY) return 'mistral';
  if (process.env.OPENAI_API_KEY) return 'openai';
  return null;
}

function fallbackResponse(request: AiRequest, start: number, note?: string): AiResponse {
  const excerpt = request.prompt.replace(/\\s+/g, ' ').slice(0, 140);
  return {
    text: \`\${note ?? '[offline demo]'} Processed \${request.prompt.length} chars: "\${excerpt}" — set ANTHROPIC_API_KEY, MISTRAL_API_KEY, or OPENAI_API_KEY for live inference.\`,
    model: 'fallback-deterministic',
    provider: 'fallback',
    fallback: true,
    latency_ms: Date.now() - start,
  };
}

async function callAnthropic(request: AiRequest): Promise<{ text: string; model: string }> {
  const model = process.env.ANTHROPIC_MODEL ?? 'claude-sonnet-5';
  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      'x-api-key': process.env.ANTHROPIC_API_KEY!,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model,
      max_tokens: 1024,
      system: request.context ?? 'You are a helpful assistant.',
      messages: [{ role: 'user', content: request.prompt }],
    }),
  });
  if (!res.ok) throw new Error(\`Anthropic \${res.status}: \${(await res.text()).slice(0, 200)}\`);
  const data = await res.json();
  return { text: data.content?.[0]?.text ?? '', model };
}

async function callOpenAiCompatible(request: AiRequest, baseUrl: string, key: string, model: string): Promise<{ text: string; model: string }> {
  const res = await fetch(\`\${baseUrl}/chat/completions\`, {
    method: 'POST',
    headers: { 'content-type': 'application/json', authorization: \`Bearer \${key}\` },
    body: JSON.stringify({
      model,
      max_tokens: 1024,
      messages: [
        { role: 'system', content: request.context ?? 'You are a helpful assistant.' },
        { role: 'user', content: request.prompt },
      ],
    }),
  });
  if (!res.ok) throw new Error(\`\${baseUrl} \${res.status}: \${(await res.text()).slice(0, 200)}\`);
  const data = await res.json();
  return { text: data.choices?.[0]?.message?.content ?? '', model };
}

export async function invokeAi(request: AiRequest): Promise<AiResponse> {
  const start = Date.now();
  const provider = detectProvider();
  if (process.env.DEMO_FALLBACK_MODE === 'true' || !provider) {
    return fallbackResponse(request, start);
  }

  try {
    let out: { text: string; model: string };
    if (provider === 'anthropic') {
      out = await callAnthropic(request);
    } else if (provider === 'mistral') {
      out = await callOpenAiCompatible(request, 'https://api.mistral.ai/v1', process.env.MISTRAL_API_KEY!, process.env.MISTRAL_MODEL ?? 'mistral-large-latest');
    } else {
      out = await callOpenAiCompatible(request, process.env.OPENAI_BASE_URL ?? 'https://api.openai.com/v1', process.env.OPENAI_API_KEY!, process.env.OPENAI_MODEL ?? 'gpt-4o-mini');
    }
    return { ...out, provider, fallback: false, latency_ms: Date.now() - start };
  } catch (e) {
    // Degrade visibly, never die mid-demo: note the provider error and fall back.
    return fallbackResponse(request, start, \`[\${provider} error: \${String(e).slice(0, 80)} — fallback]\`);
  }
}
`));

  // ─── Demo panel component ──────────────────────────────────────────────
  files.push(mkFile('src/components/demo-panel.tsx', `'use client';

import { useState } from 'react';

export function DemoPanel() {
  const [input, setInput] = useState('');
  const [output, setOutput] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  async function run() {
    setLoading(true);
    try {
      const res = await fetch('/api/process', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ input }),
      });
      const data = await res.json();
      setOutput(data.result?.text ?? JSON.stringify(data));
    } catch (e) {
      setOutput(\`Error: \${e}\`);
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="w-full max-w-xl border border-neutral-800 rounded-xl p-6">
      <textarea
        className="w-full bg-neutral-900 border border-neutral-700 rounded-lg p-3 mb-4 text-sm"
        rows={3}
        placeholder="Enter demo input..."
        value={input}
        onChange={(e) => setInput(e.target.value)}
      />
      <button
        onClick={run}
        disabled={loading}
        className="px-6 py-2 bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 rounded-lg font-medium"
      >
        {loading ? 'Processing...' : 'Run'}
      </button>
      {output && (
        <pre className="mt-4 p-4 bg-neutral-900 rounded-lg text-sm whitespace-pre-wrap">{output}</pre>
      )}
    </div>
  );
}
`));

  // ─── Process API route ─────────────────────────────────────────────────
  files.push(mkFile('src/app/api/process/route.ts', `import { NextRequest, NextResponse } from 'next/server';
import { invokeAi } from '@/core/ai/client';

export async function POST(request: NextRequest) {
  try {
    const { input } = await request.json();
    if (!input || typeof input !== 'string') {
      return NextResponse.json({ error: 'Invalid input' }, { status: 400 });
    }

    const result = await invokeAi({ prompt: input });
    return NextResponse.json({ result });
  } catch (e) {
    return NextResponse.json({ error: String(e) }, { status: 500 });
  }
}
`));

  // ─── Feature-specific files ────────────────────────────────────────────
  for (const featureId of features) {
    const comp = featureComponentName(featureId);
    const mapping = featureMapping[featureId];
    if (!mapping) continue;

    for (const route of mapping.routes) {
      const svc = mapping.services[0];
      const svcImport = svc ? '@/' + svc.replace(/^src\//, '').replace(/\.ts$/, '') : null;
      files.push(mkFile(route, `import { NextRequest, NextResponse } from 'next/server';
${svcImport ? `import { execute${comp} } from '${svcImport}';\n` : ''}
/**
 * Feature: ${featureId}
 *
 * Design contract:
 * - GET returns current state for the feature
 * - POST accepts input and delegates to the feature service
 * - All endpoints return structured JSON with error handling
 */
export async function GET(request: NextRequest) {
  return NextResponse.json({
    feature: '${featureId}',
    status: 'ok',
    mode: process.env.NODE_ENV === 'production' ? 'live' : 'demo',
  });
}

export async function POST(request: NextRequest) {
  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 });
  }
${svcImport
  ? `  const output = await execute${comp}({ data: body });
  return NextResponse.json({ feature: '${featureId}', ...output });`
  : `  // TODO: delegate to feature service
  return NextResponse.json({ feature: '${featureId}', received: body, result: 'not-implemented' });`}
}
`));
    }

    for (const ui of mapping.ui) {
      files.push(mkFile(ui, `'use client';

// Feature: ${featureId}
export function ${comp}() {
  return (
    <div className="p-4 border border-neutral-800 rounded-lg">
      <h3 className="font-semibold mb-2">${comp}</h3>
      <p className="text-sm text-neutral-400">Feature "${featureId}" — implement the UI here.</p>
    </div>
  );
}
`));
    }

    for (const service of mapping.services) {
      files.push(mkFile(service, `/**
 * Service: ${featureId}
 *
 * Wired to the AI client so the demo path produces a visible, input-dependent
 * result out of the box (offline via DEMO_FALLBACK_MODE, live with any API key).
 * Replace the prompt with the feature's real core mechanism.
 */

import { invokeAi } from '@/core/ai/client';

export interface ${comp}Input {
  data: unknown;
}

export interface ${comp}Output {
  success: boolean;
  result: {
    text: string;
    model: string;
    provider: string;
    fallback: boolean;
    latency_ms: number;
  };
}

export async function execute${comp}(input: ${comp}Input): Promise<${comp}Output> {
  const response = await invokeAi({
    prompt: \`Feature "${featureId}": process this input and return a concise, demo-ready result.\\n\\nInput: \${JSON.stringify(input.data)}\`,
    context: 'You are the "${featureId}" service of ${projectName}. Answer concisely — the output is shown live in a demo.',
  });
  return {
    success: true,
    result: {
      text: response.text,
      model: response.model,
      provider: response.provider,
      fallback: response.fallback,
      latency_ms: response.latency_ms,
    },
  };
}
`));
    }

    for (const test of mapping.tests) {
      files.push(mkFile(test, `import { describe, it } from 'vitest';

describe('${featureId}', () => {
  it.todo('implements the feature contract');
  it.todo('returns correct schema for valid input');
  it.todo('returns 400 for missing required fields');
  it.todo('fallback adapter produces deterministic output');
});
`));
    }
  }

  // ─── Demo data scripts ─────────────────────────────────────────────────
  files.push(mkFile('scripts/seed-demo-data.ts', `/**
 * Seed deterministic demo data so the demo path is reproducible.
 * Run: pnpm demo:seed
 */

const demoData = {
  seeded_at: new Date().toISOString(),
  entries: [
    { id: 'demo-1', label: 'Primary demo scenario' },
    { id: 'demo-2', label: 'Secondary demo scenario' },
    { id: 'demo-3', label: 'Edge case scenario' },
  ],
};

console.log('Demo data seeded:', JSON.stringify(demoData, null, 2));
// TODO: write to your data store (file, DB, etc.)
`));

  files.push(mkFile('scripts/reset-demo-data.ts', `/**
 * Reset demo state to a clean, deterministic baseline.
 * Run before every demo rehearsal and the actual demo.
 * Run: pnpm demo:reset
 */

console.log('Demo state reset to baseline.');
// TODO: reset your data store to the seeded state
`));

  // ─── Smoke test ────────────────────────────────────────────────────────
  files.push(mkFile('tests/smoke.test.ts', `import { describe, it, expect } from 'vitest';
import { existsSync } from 'node:fs';
import { join } from 'node:path';

describe('smoke: ${projectName}', () => {
  it('has a package.json', () => {
    expect(existsSync(join(process.cwd(), 'package.json'))).toBe(true);
  });

  it('has an env template', () => {
    expect(existsSync(join(process.cwd(), '.env.example'))).toBe(true);
  });

  it('has a health endpoint', () => {
    expect(existsSync(join(process.cwd(), 'src/app/api/health/route.ts'))).toBe(true);
  });

  it('has demo reset script', () => {
    expect(existsSync(join(process.cwd(), 'scripts/reset-demo-data.ts'))).toBe(true);
  });
});
`));

  // ─── Demo path test ────────────────────────────────────────────────────
  const demoStepsComment = demoFlow
    .map((s) => ` * Step ${s.step}: ${s.user_action} → ${s.system_response} (proof: ${s.proof_shown})`)
    .join('\n');

  files.push(mkFile('tests/demo-path.test.ts', `import { describe, it, expect } from 'vitest';

/**
 * Demo path validation — mirrors the locked demo flow.
${demoStepsComment}
 *
 * Wow moment: ${wowMoment ?? 'TBD'}
 */
describe('demo path', () => {
  it('demo flow steps are documented', () => {
    const steps = ${JSON.stringify(demoFlow.map((s) => s.step))};
    expect(steps.length).toBeGreaterThan(0);
  });

  it('fallback mode produces deterministic output', async () => {
    process.env.DEMO_FALLBACK_MODE = 'true';
    const { invokeAi } = await import('../src/core/ai/client');
    const res = await invokeAi({ prompt: 'demo test' });
    expect(res.fallback).toBe(true);
    expect(res.text.length).toBeGreaterThan(0);
  });
});
`));

  // ─── Vitest config ─────────────────────────────────────────────────────
  files.push(mkFile('vitest.config.ts', `import { defineConfig } from 'vitest/config';
import { resolve } from 'node:path';

export default defineConfig({
  test: {
    environment: 'node',
    include: ['tests/**/*.test.ts'],
  },
  resolve: {
    alias: { '@': resolve(__dirname, './src') },
  },
});
`));

  // ─── PostCSS + Tailwind ────────────────────────────────────────────────
  files.push(mkFile('postcss.config.mjs', `const config = {
  plugins: ['@tailwindcss/postcss'],
};

export default config;
`));

  // ─── Deployment config ─────────────────────────────────────────────────
  files.push(mkFile('vercel.json', JSON.stringify({
    framework: 'nextjs',
    buildCommand: 'next build',
    outputDirectory: '.next',
  }, null, 2) + '\n'));

  // ─── README ────────────────────────────────────────────────────────────
  files.push(mkFile('README.md', `# ${projectName}

Generated by the HADK scaffold engine (profile: web-ai-fullstack).

## Quick Start

\`\`\`bash
pnpm install
cp .env.example .env.local   # fallback mode enabled by default
pnpm dev
\`\`\`

Open http://localhost:3000 — the demo works without API keys (fallback mode).

## Demo

\`\`\`bash
pnpm demo:seed     # load deterministic demo data
pnpm demo:reset    # reset state before each demo run
\`\`\`

## Health Check

\`\`\`bash
curl http://localhost:3000/api/health
\`\`\`

## Tests

\`\`\`bash
pnpm test          # smoke + demo-path tests
pnpm typecheck
\`\`\`

## Deploy

\`\`\`bash
npx vercel --prod
\`\`\`
`));

  // ─── gitignore ─────────────────────────────────────────────────────────
  files.push(mkFile('.gitignore', `node_modules/
.next/
.env.local
*.tsbuildinfo
coverage/
`));

  return files;
}

function mapFeature(featureId: string, featureName: string): FeatureMapping {
  const comp = featureComponentName(featureId);
  const slug = featureId.replace(/_/g, '-');
  return {
    routes: [`src/app/api/${slug}/route.ts`],
    ui: [`src/components/${slug}.tsx`],
    services: [`src/core/${slug}/service.ts`],
    tests: [`tests/${slug}.test.ts`],
  };
}

export const webAiFullstackProfile: ProfileDefinition = {
  name: 'web-ai-fullstack',
  description: 'Next.js full-stack with AI integration, Tailwind, fallback mode, and demo tooling',
  stack: ['next.js', 'react', 'typescript', 'tailwind', 'openai', 'vitest'],
  startupCommand: 'pnpm dev',
  healthCheck: 'curl http://localhost:3000/api/health',
  postInstallCommands: ['pnpm demo:seed'],
  generateFiles,
  mapFeature,
};
